### ISSUE TITLE
[epic] - Improved and Manual Cert Rotation

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#2636]
This topic may require some more design discussion. (See comments below)
We may want to support that when certs are about to expire warn the user in logs and automatically rotate them. We can add jitter to not restart all nodes at the same time when restarting in order to get the rotation done.
We WILL need to support manual one-click cert rotation like we have today in Rancher with RKE.

This is also needed for RKE2 as well, see https://github.com/rancher/rke2/issues/570

For additional context, here is what the UI looks like in Rancher 2.5.3 currently:
![image](https://user-images.githubusercontent.com/45179589/101402648-412fd800-3891-11eb-8690-11e4a70622b5.png)

As you can see the user can rotate certs for etcd, kubelet, kube-apiserver, kube-proxy, kube-scheduler, kube-controller-manager.
CA certs cannot be rotated via the UI. These has to be done manually today such as with RKE via the cli.

**Issues to track**
- [x] https://github.com/k3s-io/k3s/issues/4349
- [x] https://github.com/k3s-io/k3s/issues/4271
- [x] https://github.com/k3s-io/k3s/issues/4381
- [x] https://github.com/k3s-io/k3s/issues/4382

**Comment by cjellick** [comment]
We just had a design call to flesh this out. Here are the key takeaways:

Next step is for @erikwilson to digest these notes and our discussion and come back with a formalized design doc for the team to approved.

Things we want to see in design doc (beyond baseline desgin):
- Dataflow diagram for k3s and rke2's current cert bootstrapping and rotation functionality
- k3s/rke2's current support for supplying your own certificates and assesment of how this change/enhancement will impact that.

Feature requirements (and non-requirements):
Manual rotation
- When a k3s/rke2 cluster is imported into Rancher a user should be able to rotate all control-plane component certificates or select an individual component's cert to rotate. This includes etcd.
- Rotating certificates from outside of Rancher does not need a dedicate CLI command, but the process to do so must be clearly documented. So, a documentation change is part of this feature.

Automated rotation:
- We did not explicitly and conclusively agree on whether this happens only when a cluster is integrated with Rancher or if it happens with standalone k3s clusters. However, I believe we leaned to having Rancher do this, since that is comparable to how RKE1 behaves.

Implementation details discussed:
- Leverage system-upgrade-controller framework to trigger a job on each host.
- Prefer k3s/rke2 native cert generation commands rather than wrapping openssl commands

**Comment by cjellick** [comment]
For custom certificates, rke1 standalone supports "Generating Certificate Signing Requests (CSRs) and Keyslink". We need to understand if this is in scope for parity. I will work work with PM to figure that out.

**Comment by endianjoakim** [comment]
Unclear where to add this, but if I may feature creep a bit regarding certificate rotation it would be great to be able to configure both the certificates' lifetimes (more than 1 year) and trigger period for rotation (other than 90 days prior to expiration). 

Some context, we're considering using k3s for an on-premise offline system with a system lifetime counted in decades. A manual command for rotating certificates would solve some parts of the issues we're seeing but the ability to set a longer certificate lifetime would be very helpful.

**Comment by briandowns** [comment]
The coming functionality will provide the user/operator the ability to rotate certificates bases on service or all certificates as well as the ability to extend the expiry of all or a given certificate. We're expecting this to land in the December release.

**Comment by cjellick** [comment]
Needed in 1.21 as well. Please open backport issue.

**Comment by briandowns** [comment]
This epic is still semi active as there are more features to add to k3s/rke2 in the scope of cert rotation.

**Comment by katran001** [comment]
Continue to leave this open for the team to use as a reference when adding new issues for current/future work associated with it. Moving this to the next milestone.
