### ISSUE TITLE
[Epic] Create CLI to automate parts of release processes

### ISSUE THREAD

**Issue by cwayne18** [k3s-io/k3s#4912]
As we push towards fully automating our release process, a great first step would be to collate a list of scripts that automate small pieces of the process (i.e. automatically open a PR to mark the latest release stable, update all charts for RKE2, create KDM PR's).  This issue will act as an overarching tracker to schedule individual scripts/commands as well as a general design of such a cli.

* Opened issues:
- [ ]  https://github.com/rancher/rke2/issues/2077
- [ ] https://github.com/k3s-io/k3s/issues/4150
- [x]  https://github.com/rancher/rke2/issues/1904
- [x] https://github.com/rancher/rke2/issues/2305
- [x] https://github.com/k3s-io/k3s/issues/3907
- [ ] https://github.com/k3s-io/k3s/issues/3582
- [ ] https://github.com/k3s-io/k3s/issues/3581
- [ ] https://github.com/k3s-io/k3s/issues/2956
- [ ] https://github.com/k3s-io/k3s/issues/4913
