### ISSUE TITLE
[Epic] Integration/e2e test additions

### ISSUE THREAD

**Issue by cwayne18** [k3s-io/k3s#6070]
I'd like to use this to track this cycle's requested test additions/enhancements for k3s

**New Test Requests** 
- [x] https://github.com/k3s-io/k3s/issues/6062
- [x] https://github.com/k3s-io/k3s/issues/7441
- [x] https://github.com/k3s-io/k3s/issues/6061
- [x] https://github.com/k3s-io/k3s/issues/6060
- [x] https://github.com/k3s-io/k3s/issues/6058
- [x] https://github.com/k3s-io/k3s/issues/6057
- [x] https://github.com/k3s-io/k3s/issues/6056
- [x] https://github.com/k3s-io/k3s/issues/8049
- [x] https://github.com/k3s-io/k3s/issues/2955
- [x] https://github.com/k3s-io/k3s/issues/8051
**Test Enhancements**
- [x] https://github.com/k3s-io/k3s/issues/8091

**Comment by dereknola** [comment]
Closing this as done... transfering the few remaining open issues to https://github.com/k3s-io/k3s/issues/9477
