### ISSUE TITLE
[Epic] Testing Overhaul 2024

### ISSUE THREAD

**Issue by dereknola** [k3s-io/k3s#9477]
This is an epic to track all the changes for testing in Q1 2024. 

- [ ] Unit tests should no longer be in a matrix, and take up too much cache space

- [ ] Move E2E into GH Actions on regular ubuntu runners

- [ ] Move parts of the Docker tests into GH Actions

- [ ] Update all upload/download artifacts actions to v4 (not backward compatible with v3)

- [ ] Create ADR giving more details on all of the above
